### PR TITLE
Update index.html

### PR DESCRIPTION
**Pull request by postphotos**
Do I sound desperate, @davidnuon? 😄

### CODE REVIEW

**Comment by MasterKale** [comment]
@postphotos you also need to contribute a 90's-era web badge!

**Comment by postphotos** [comment]
~OnIt.gif~

**Comment by MasterKale** [comment]
Disregard! Apologies, I thought this was the httpsters repo!

**Comment by postphotos** [comment]
@MasterKale, you raised a good point. Can you provide feedback on this [related issue](https://github.com/therealhttpsters/therealhttpsters.github.io/pull/4)? Cheers.

**Comment by davidnuon** [comment]
I'll abide by this. lgtm.

**Pull request merged**
